name: check-pr

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.1_beta.app/Contents/Developer'

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: swift build

      - name: Test
        run: swift test
        
      - name: Lint with cocoapods
        run: pod lib lint --allow-warnings